//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALIEBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALIEBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Characters&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;clarke&quot;,
        ///      &quot;Name&quot;: &quot;Clarke Griffin&quot;,
        ///      &quot;Description&quot;: &quot;Clarke is strong and determined. Her friends and family are her weakness. She is not as clever as Raven, though she is resourceful.&quot;,
        ///      &quot;Age&quot;: &quot;18&quot;,
        ///      &quot;LivingRelatives&quot;: &quot;Dr. Abigail Griffin&quot;,
        ///      &quot;Kills&quot;: &quot;1000+&quot;,
        ///      &quot;Skills&quot;: &quot;Negotiation, Medical Knowledge&quot;,
        ///      &quot;Quote&quot;: &quot;I did it for my people.&quot;,
        ///      &quot;DescriptionLink&quot;: &quot;...&quot;,
        ///      &quot;ImageLink&quot;: &quot;http://vignette3.wikia.nocook [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSONCharacters {
            get {
                return ResourceManager.GetString("JSONCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Locations&quot; : [
        ///      {
        ///        &quot;id&quot;:&quot;tondc&quot;,
        ///          &quot;Name&quot; : &quot;Tondc aka Tondisi&quot;,
        ///        &quot;Description&quot; : &quot;Tondc, formally Washington D.C., the 2052 capital of the United States, was the Tri Kru&apos;s largest village; until Mount Weather shot a missle destroying much of the city and killing at least 250 people&quot;,
        ///        &quot;ImageLink&quot; : &quot;http://vignette2.wikia.nocookie.net/thehundred/images/a/ad/Tondc_after_missile_2x12.png/revision/latest?cb=20150819003729&quot;
        ///        },
        ///        {
        ///          &quot;id&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSONLocations {
            get {
                return ResourceManager.GetString("JSONLocations", resourceCulture);
            }
        }
    }
}
